# Generated by Django 4.1.3 on 2022-12-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=20, verbose_name='Name')),
                ('body', models.CharField(db_index=True, max_length=200, verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('files', models.FileField(blank=True, null=True, upload_to='', verbose_name='Files')),
                ('likes', models.PositiveIntegerField(verbose_name='Likes')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
